const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}

module.exports = {
    SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicU14SDQ2WmNmcTJNclhYYkZjbHl2R1F3c1hXVXNwQlhKSFNWd0xIQzVXST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid2wyaUpuSXc3UENqVjM3QzQyT3ZqSWhOVWlyNVB6Und3UEd2NDV4UFdHVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTQWRaSEhBWEwvcFh1bm9Nc3dqTHFwZDRwdHZQZENQSVUyWjBFR3dFdFY0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJqTGZyUlY3TnFzQTFIODh2Mm5SejRYZXh4U1JRR0M4T0UrejhIVUM2T1MwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjBHbkdtTEk2OU5Zb2I4MzBZdWhXSHFPOW52dGRIRW1sbFlxSWpYaUp5bEE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InRINlZ1Qkh2M2NDc3UwNFcwLzdmcVd5WjhuYnRPUlhVQWFQeDhsNVRwVUU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUxkTWpCMTlITE9PZjdQZVMrWENkTDg1K3ppbmFjRHZTQmkrc1B1MFdscz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoib1lFRHN1SEtEeHlpRWUwRitVYlVjazYrZ0d0VjQ2OFpFL1ZwVjAzeERVST0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ii9mSkFSVHNPcXNTLzNJUHNXWFFLQmp0VEo5SkNXdXZFSHJ6WS84SEpLWTh6d0hIVzZ6dnI2R0crcWltZnZmNzZjaE9vU0pvUW1zUnBkOGJEOCtnMGhnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODIsImFkdlNlY3JldEtleSI6Ikg2T1hjMEc5YkR3U3lkd0Y1dmZKdDBCamZXL1B6ZmVRV3ZNalBIL09iMzA9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IkZpeGduNXpVUTllajBpQWYzSlphR2ciLCJwaG9uZUlkIjoiZDkyNGJiZTItZGQyMC00NDU1LWIzMjItMTQ3MDlkNjNlMmNkIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkhablNFZGVUYTBWRmZXM2VUbHczTmY1U3Q3WT0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI3SkFaZmJ3NkJ2LzRCU0tLcFNkU3dPZlFpS3M9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiOFJZVkdTMzMiLCJtZSI6eyJpZCI6IjI1NTYyNDE0MzczOTozOEBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDS0sreTlRQkVKWGsxcnNHR0FJZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiTUVzOFZadWsrMFRKRjlUK2Qrd0x3K1NWQmhWT3cwSmoyRUJpN0orZCtCST0iLCJhY2NvdW50U2lnbmF0dXJlIjoiM2JrTk1kNUlGb2JQbTNJSWhBSUZhMG96VUhiem8yWTlHRklIaXNyUy8zOWRvRno5MlBJTzRkazFwNWpxYnQvZ2UwMElQS1cydzJSUnc3d1lheDAxQmc9PSIsImRldmljZVNpZ25hdHVyZSI6Ijl4bkdUck1IM0JjZmxseUx6dTZqaFRpSS9wUGNNclVpdHBDNGg3V0kwOWlJRWVMVzVsYjFJaUN1SUNWK2ZzMnFYTXhHdzFTdXQ1QWU3aTJ0SWUrWWl3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU1NjI0MTQzNzM5OjM4QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlRCTFBGV2JwUHRFeVJmVS9uZnNDOFBrbFFZVlRzTkNZOWhBWXV5Zm5mZ1MifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzU3NjY1NjIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBQ3pyIn0=",
    CAPTION: process.env.CAPTION || "code by yessertech ",
    AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || "true",
    AUTO_REPLY_STATUS: process.env.AUTO_REPLY_STATUS || "true",
    READ_MESSAGE: process.env.READ_MESSAGE || "true", // Added auto-read configuration
    MODE: process.env.MODE || "public",
    AUTO_VOICE: process.env.AUTO_VOICE || "true",
    AUTO_STICKER: process.env.AUTO_STICKER || "false",
    AUTO_REPLY: process.env.AUTO_REPLY || "false",
    ALIVE_IMG: process.env.ALIVE_IMG || "https://files.catbox.moe/3kdkf6.jpg",
    ALIVE_MSG: process.env.ALIVE_MSG || "HII DEAR IM ONLINE I'M YESSER-MD WHATSAPP BOT 👍🤠",
    ANTI_LINK: process.env.ANTI_LINK || "true",
    ANTI_BAD: process.env.ANTI_BAD || "true",
    PREFIX: process.env.PREFIX || ".",
    FAKE_RECORDING: process.env.FAKE_RECORDING || "true",
    FAKE_TYPING: process.env.FAKE_TYPING || "false",
    ALWAYS_ONLINE: process.env.ALWAYS_ONLINE || "true",
    CURRENT_STATUS: process.env.CURRENT_STATUS || "true",
    AUTO_REACT: process.env.AUTO_REACT || "true",
    HEART_REACT: process.env.HEART_REACT || "true",
    OWNER_REACT: process.env.OWNER_REACT || "true",
    BOT_NAME: process.env.BOT_NAME || "yessertech",
    STATUS_REPLY: process.env.STATUS_REPLY || "`✅ your status seen 👀`",
    OMDB_API_KEY: process.env.OMDB_API_KEY || "76cb7f39", // omdbapi.com
};
